#!/usr/bin/env bash
#MISE description="Run CLI"
#MISE dir="{{config_root}}/packages/cli"
set -e

deno run --allow-read --allow-write --allow-net --allow-run --allow-ffi --allow-env --allow-sys src/main.ts "$@"
