use jiji_config::{
    build_config_path, get_available_configs, template_engine, validate_yaml, ConfigError, TEMPLATE,
};
use jiji_tui::Ui;
use sha2::{Digest, Sha256};
use std::fs;
use std::path::Path;
use std::process::{Command, Stdio};

pub fn run(environment: Option<&str>) -> anyhow::Result<()> {
    Ui::section("Configuration Initialization:");

    let config_path = build_config_path(environment);
    Ui::say(&format!("Target: {}", config_path.display()), 1);

    let existing = get_available_configs(Path::new("."));
    if !existing.is_empty() {
        Ui::say(&format!("Existing configurations ({}):", existing.len()), 1);
        for cfg in &existing {
            Ui::say(&cfg.display().to_string(), 2);
        }
    }

    if config_path.exists() {
        Ui::warn(&format!(
            "Configuration already exists at {}",
            config_path.display()
        ));
        let overwrite = Ui::confirm(
            &format!(
                "Config file already exists at {}. Overwrite it?",
                config_path.display()
            ),
            false,
        )?;
        if !overwrite {
            Ui::say("Init command cancelled by user", 0);
            return Ok(());
        }
        Ui::say("Existing configuration will be replaced.", 1);
    }

    Ui::section("Creating Configuration:");
    Ui::say("Loading default configuration template", 1);
    let project_root = std::env::current_dir()?;
    let template = render_template(&project_root);

    Ui::say("Writing configuration file", 1);
    if let Some(parent) = config_path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(&config_path, &template)?;
    Ui::say(&format!("Created: {}", config_path.display()), 1);

    Ui::section("Validation:");
    Ui::say("Validating configuration", 1);
    let raw: serde_yaml::Value =
        serde_yaml::from_str(&template).map_err(|source| ConfigError::Load {
            path: config_path.display().to_string(),
            source,
        })?;
    let result = validate_yaml(&raw);
    if result.valid {
        Ui::say("Configuration is valid", 1);
        if !result.warnings.is_empty() {
            Ui::say(&format!("Warnings ({}):", result.warnings.len()), 1);
            for w in &result.warnings {
                Ui::say(&format!("{}: {}", w.path, w.message), 2);
            }
        }
    } else {
        Ui::error(&format!(
            "Configuration validation failed with {} error(s):",
            result.errors.len()
        ));
        for e in &result.errors {
            Ui::say(&format!("{}: {}", e.path, e.message), 1);
        }
        let joined = result
            .errors
            .iter()
            .map(|e| format!("{}: {}", e.path, e.message))
            .collect::<Vec<_>>()
            .join("\n");
        return Err(ConfigError::Invalid(joined).into());
    }

    if let Some(engine) = template_engine() {
        Ui::say(&format!("Checking {engine} availability"), 1);
        if engine_available(engine) {
            Ui::say(&format!("{engine} is available"), 1);
        } else {
            Ui::warn(&format!("{engine} is not available on this system"));
            Ui::say(
                &format!("Install {engine}, or select another engine in the configuration."),
                1,
            );
        }
    }

    Ui::section("Next Steps:");
    Ui::say("1. Review the generated configuration.", 1);
    Ui::say("2. Configure services, servers, and secrets.", 1);
    Ui::say("3. Run `jiji server setup` to prepare the servers.", 1);
    Ui::say("4. Run `jiji deploy`.", 1);

    Ui::success(&format!(
        "\nConfiguration file created: {}",
        config_path.display()
    ));

    Ok(())
}

fn render_template(project_root: &Path) -> String {
    let (management_cidr, container_cidr) = project_cidrs(project_root);
    TEMPLATE.replacen(
        "# network:\n\
         #   # Enable private networking (default: true)\n\
         #   enabled: true\n\
         #\n\
         #   # Optional, non-overlapping address ranges\n\
         #   management_cidr: \"198.18.0.0/16\"\n\
         #   container_cidr: \"100.64.0.0/10\"",
        &format!(
            "network:\n\
             \x20 # Project-specific ranges generated by `jiji init`. Keep them unique across projects\n\
             \x20 # sharing infrastructure, and verify they do not overlap a LAN, VPN, or cloud VPC.\n\
             \x20 enabled: true\n\
             \x20 management_cidr: \"{management_cidr}\"\n\
             \x20 container_cidr: \"{container_cidr}\""
        ),
        1,
    )
}

fn project_cidrs(project_root: &Path) -> (String, String) {
    let mut hasher = Sha256::new();
    hasher.update(project_root.as_os_str().as_encoded_bytes());
    let slot = hasher.finalize()[0] % 64;
    (
        format!("198.18.{slot}.0/24"),
        format!("100.{}.0.0/16", 64 + slot),
    )
}

/// Checks engine availability by running `{engine} --version` and checking the exit code.
fn engine_available(engine: &str) -> bool {
    Command::new(engine)
        .arg("--version")
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()
        .map(|status| status.success())
        .unwrap_or(false)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn project_cidrs_are_stable_and_within_the_shared_default_pools() {
        let root = Path::new("/srv/projects/example");
        let first = project_cidrs(root);
        let second = project_cidrs(root);

        assert_eq!(first, second);
        assert!(first.0.starts_with("198.18."));
        assert!(first.0.ends_with(".0/24"));

        let container_octet = first
            .1
            .strip_prefix("100.")
            .and_then(|cidr| cidr.strip_suffix(".0.0/16"))
            .and_then(|octet| octet.parse::<u8>().ok())
            .expect("container CIDR should have the generated shape");
        assert!((64..=127).contains(&container_octet));
    }

    #[test]
    fn rendered_template_persists_generated_network_ranges() {
        let rendered = render_template(Path::new("/srv/projects/example"));
        let (management_cidr, container_cidr) = project_cidrs(Path::new("/srv/projects/example"));

        assert!(rendered.contains(&format!("management_cidr: \"{management_cidr}\"")));
        assert!(rendered.contains(&format!("container_cidr: \"{container_cidr}\"")));
        assert!(rendered.contains("\nnetwork:\n  # Project-specific ranges"));
    }
}
