pub const DEFAULT_LOCAL_REGISTRY_PORT: u16 = 31270;
pub const DEFAULT_MANAGEMENT_POOL_PREFIX: [u8; 2] = [198, 18];
pub const DEFAULT_CONTAINER_POOL_PREFIX: [u8; 2] = [100, 64];
pub const DEFAULT_SERVICE_DOMAIN: &str = "jiji";
