[package]
name = "jiji-ssh"
version = "0.4.9"
edition.workspace = true
license.workspace = true

[dependencies]
russh.workspace = true
russh-sftp = "2.3.0"
thiserror.workspace = true
tokio = { workspace = true, features = ["net", "time", "sync", "macros", "rt-multi-thread", "process", "io-util", "fs"] }

[dev-dependencies]
tempfile.workspace = true
rand = "0.10"
